# Generated by Django 4.0.4 on 2022-06-24 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='edit_content',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='edited',
        ),
    ]
